# Generated by Django 5.1.2 on 2024-10-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairsapp', '0002_rename_geeksmodel_viewdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewdata',
            old_name='title',
            new_name='name',
        ),
    ]
