# Generated by Django 5.1.2 on 2024-10-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='viewdata',
        ),
    ]
