# Generated by Django 5.1.2 on 2024-10-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairsapp', '0003_rename_title_viewdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
